openapi: 3.0.0
info:
  description: |
    API de produtos perecíveis.
    Encontra aqui os produtos perecíveis que estão perto do fim de validade e contriui para a redução de alimentos desperdiçados
    url: https://virtserver.swaggerhub.co
  version: "1.0.0"
  title: Gestão de Produtos Perecíveis
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  # Added by API Auto Mocking Plugin
  - description: Encontra aqui os produtos perecíveis que estão perto do fim de validade e contriui para a redução de alimentos desperdiçados
    url: https://virtserver.swaggerhub.com/RAQUELALMEIDA15/promo-validade/1.0.0
  - url: 'https://promovalidade.swagger.io/v2'
tags:
  - name: produto
    description: Operação de produtos perecíveis
  - name: utilizador
    description: Operação dos utilizadores
paths:
  /produto:
    post:
      tags:
        - produto
      summary: Adicionar um novo produto
      operationId: addProduto
      responses:
        '200':
          description: Produto adicionado com sucesso
        '400':
          description: Request body do produto invalido
        '401':
          description: Sem autorização
      security:
        - promovalidade_auth:
            - 'write:produtos'
            - 'read:produtos'
      requestBody:
        $ref: '#/components/requestBodies/Produto'
  '/produto/{produtoId}':
    get:
      tags:
        - produto
      summary: Encontrar um produto pelo produtoId
      description: Returna um unico produto mais detalhado
      operationId: getProdutoById
      parameters:
        - name: produtoId
          in: path
          description: produtoId necessario
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Produto enviado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
            application/xml:
              schema:
                $ref: '#/components/schemas/Produto'
        '400':
          description: Erro no envio da informação do produto
        '404':
          description: Produto não encontrado {produtoId invalido}
      security:
        - api_key: []
    put:
      tags:
        - produto
      summary: Atualizar um produto atraves do produtoId
      operationId: updateProduto
      parameters:
        - name: produtoId
          in: path
          description: produtoId necessario
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Produto atualizado com sucesso
        '400':
          description:   Erro na atualização do produto
        '404':
          description: Produto não encontrado {produtoId invalido}
      security:
        - promovalidade_auth:
            - 'write:produtos'
            - 'read:produtos'
      requestBody:
        $ref: '#/components/requestBodies/Produto'
    delete:
      tags:
        - produto
      summary: Eliminar um produto pelo produtoId
      operationId: deleteProduto
      parameters:
        - name: produtoId
          in: path
          description: produtoId necessario para eliminar
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Produto eliminado com sucesso
        '400':
          description: produtoId invalido
        '404':
          description: Produto não encontrado
      security:
        - promovalidade_auth:
            - 'write:produtos'
            - 'read:produtos'
  /produto/listProduto:
    get:
      tags: 
        - produto
      summary: Listar todos os produtos
      description: Retorna todos os produtos na base dados
      operationId: getListProdutos
      responses:
        '200':
          description: Lista de produtos enviados
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListaProdutos'
            application/xml:
              schema:
                $ref: '#/components/schemas/ListaProdutos'
        '400':
          description: Erro ao enviar lista
        '404':
          description: Não existem produtos na base de dados
  /produto/listPrecoMedio:
    get:
      tags: 
        - produto
      summary: Listar produtos com o preço medio
      description: Retorna todos os produtos e o seu preço medio
      operationId: getListPrecoMedio
      responses:
        '200':
          description: Lista dos produtos com o preco medio enviado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListaPrecoMedio'
            application/xml:
              schema:
                $ref: '#/components/schemas/ListaPrecoMedio'
        '400':
          description: Erro ao enviar a lista
        '404':
          description: Não existem produtos na base dados
  '/produto/findByCategoria/{categoria}':
    get:
      tags:
        - produto
      summary: Encontrar produtos por categoria
      description: Multiplos produtos enviados consoante a categoria selecionada
      operationId: findByCategoria
      parameters:
        - name: categoria
          in: path
          description: É necessário o envio da categoria para puder ser enviado a lista de produtos correta
          required: true
          explode: true
          schema:
            type: array
            items:
              type: string
              default: todos
      responses:
        '200':
          description: Lista de produtos enviado consoante a categoria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListaProdutos'
            application/xml:
              schema:
                $ref: '#/components/schemas/ListaProdutos'
        '400':
          description: Invalido
        '404':
          description: Categoria não foi encontrado
  /produto/listarNaoDesperdicados:
    get:
      tags:
        - produto
      summary: Listar todos os produtos e as suas quantidades não desperdicadas
      description: Listar todos os produtos e as suas quantidades não desperdicadas, divido por peso liquido e peso bruto
      operationId: getListProdutosNaoDesperdicados
      responses:
        '200':
          description: Lista de produtos não desperdicados enviada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListaProdutosNaoDesperdicados'
            application/xml:
              schema:
                $ref: '#/components/schemas/ListaProdutosNaoDesperdicados'
        '400':
          description: Erro ao enviar a lista
        '404':
          description: Não existe produtos na base de dados
  /produto/associarProdutoUtilizador:
    post:
      tags: 
        - produto
      summary: Associar um produto ao cliente
      description: Associar um ou mais produtos a lista de favoritos do cliente
      operationId: associarProdutoCliente
      responses:
        '200':
          description: Associação feita com sucesso
        '400':
          description: Erro
        '404':
          description: Utilizador invalido
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssociarProdutoCliente'
          application/xml:
            schema:
              $ref: '#/components/schemas/AssociarProdutoCliente'
  '/produto/associarProdutoUtilizador/{utilizadorId}':
    get:
      tags: 
        - produto
      summary: Listar produtos favoritos do utilizador
      description: Lista com algum detalhe os produtos favoritos do utilizador
      operationId: listarAssociarProdutoUtilizador
      parameters:
        - name: utilizadorId
          in: path
          description: É necessário o envio do utilizadorId para puder ser enviado a lista de produtos correta
          required: true
          explode: true
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: Enviada a lista com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListaProdutosAssociados'
            application/xml:
              schema:
                $ref: '#/components/schemas/ListaProdutosAssociados'
        '400':
          description: Erro
        '404':
          description: Utilizador não foi encontrado
  /utilizador:
    post:
      tags:
        - utilizador
      summary: Criar utilizador
      description: Criação de um novo utilizador
      operationId: createUtilizador
      responses:
        '200':
          description: Utilizador criado com sucesso
        '400':
          description: Erro na criacao de um utilizador
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Utilizador'
          application/xml:
            schema:
              $ref: '#/components/schemas/Utilizador'
        required: true
  /utilizador/login:
    get:
      tags:
        - utilizador
      summary: Login do utilizador
      operationId: loginUtilizador
      parameters:
        - name: utilizador
          in: query
          description: nome do utilizador
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: palavra passe do utilizador
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
        '400':
          description: Utilizador invalido
  /utilizador/logout:
    get:
      tags:
        - utilizador
      summary: Logout do utilizador
      operationId: logoutUtilizador
      responses:
        default:
          description: successful operation
  '/utilizador/{email}':
    get:
      tags:
        - utilizador
      summary: Encontrar utilizador
      operationId: getUtilizadorByEmail
      parameters:
        - name: email
          in: path
          description: Necessario enviar o email do utilizador pretendido
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Enviado utilizador coom sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Utilizador'
            application/xml:
              schema:
                $ref: '#/components/schemas/Utilizador'
        '400':
          description: Erro ao enviar o utilizador
        '404':
          description: Utilizador não encontrado
    patch:
      tags:
        - utilizador
      summary: Updated utilizador
      description: So consegue ser realizado por um utilizador logado
      operationId: updateUtilizador
      parameters:
        - name: email
          in: path
          description: email do utilizador necessario
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Atualizado utilizador com sucesso
        '400':
          description: Erro ao atualizar
        '404':
          description: Utilizador não foi encontrado
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Utilizador'
          application/xml:
            schema:
              $ref: '#/components/schemas/Utilizador'
        required: true
    delete:
      tags:
        - utilizador
      summary: Eliminar utilizador
      description: So consegue ser realizado por um utilizador logado
      operationId: deleteUtilizador
      parameters:
        - name: email
          in: path
          description: email necessario
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Elimiado com sucesso
        '400':
          description: Erro
        '404':
          description: Utilizador não encontrado
      security:
        - promovalidade_auth:
            - 'write:utilizador'
            - 'read:utilizador'
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
#inicio dos componentes que depois referenciamos /components/schemas/oquequisermosreferenciar
components:
  schemas:
    #json produto 
    Produto:
      type: object
      properties:
        produtoId:
          type: string
        nome:
          type: string
        categoria:
          $ref: '#/components/schemas/Categoria'
        informacao:
          $ref: '#/components/schemas/Informacao'
        precoUnitario:
          type: number
        precoPromocional:
          type: number
        percentagemDesconto:
          type: number
        precoKilo:
          type: number
        informacaoNutricional:
          $ref: '#/components/schemas/InformacaoNutricional'
        origem: 
          type: string
        nutricaoPontuacao:
          type: string
        data: 
          $ref: '#/components/schemas/Data'
        codigoBarras:
          type: number
      required: 
        - produtoId
        - nome
        - categoria
        - informacao
        - precoUnitario
        - precoPromocional
        - percentagemDesconto
        - precoKilo
        - informacaoNutricional
        - origem
        - nutricaoPontuacao
        - data
        - codigoBarras
      #xml produto
      xml:
        name: Produto
    #json informacao
    Informacao:
      type: object
      properties:
        informacaoCurta:
          type: string
          maxLength: 150
        informacaoComprida:
          type: string
      xml: 
        name: informacao
    # json referencia detalhe
    Detalhe:
      type: object
      properties:
        nome:
          type: string
        descricao:
          type: string
        codigo: 
          type: string
        precoUnitario:
          type: number
        precoKilo:
          type: number
      xml: 
        name: detalhe  
    #json referencia categoria
    Categoria:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required: 
        - id
        - name
      #xml categoria
      xml:
        name: Categoria
    #json informacao nutricional
    InformacaoNutricional:
      type: object
      properties:
        peso:
          type: number
        energia:
          type: number
        lipidos:
          type: number
        saturados:
          type: number
        hidratosDeCarbono:
          type: number
        acucar:
          type: number
        proteina:
          type: number
        sal:
          type: number
      xml:
        name: informacaoNutricional
    #json referencia data
    Data:
      type: object
      properties:
        dataValidade:
          type: string
          format: date
        dataProducao:
          type: string
          format: date
      #xml categoria
      xml:
        name: data
    #json PrecoMedio
    ListaPrecoMedio:
      type: array
      minItems: 0
      items:
        type: object
        properties:
          produtoId:
            type: number
          precoMedio:
            type: integer
          detalhe:
            $ref: '#/components/schemas/Detalhe'
      #xml PrecoMedio   
      xml:
        name: ListaPrecoMedio
    #json lista de produtos para venda
    ListaProdutos:
      type: array
      minItems: 0
      items:
        type: object
        properties:
          produto:
            $ref: '#/components/schemas/Produto'
      required:
        - produto
      #xml produto
      xml:
        name: Produto
    #json associas produto ao cliente
    AssociarProdutoCliente:
      type: object
      properties:
        utilizadorId:
          type: number
        listaProduto: 
          type: array
          minItems: 1
          uniqueItems: true
          items:
            type: object
            properties:
              produtoId:
                type: number
            required: 
              - produtoId
      #xml associas produto ao cliente
      xml:
        name: AssociarProdutoCliente
    #json lista Produtos Associados
    ListaProdutosAssociados:
      type: object
      properties:
        utilizadorId:
          type: number
        listaProduto: 
          type: array
          minItems: 0
          items:
            type: object
            properties:
              produto:
                $ref: '#/components/schemas/Detalhe'
            required: 
              - produto
      #xml lista Produtos Associados
      xml:
        name: ListaProdutosAssociados
    #json lista Produtos nao desperdicados
    ListaProdutosNaoDesperdicados:
      type: array
      minItems: 0
      items:
        properties:
          produtoId:
            type: number
          nome: 
            type: string
          valorPoupado: 
            type: number
          quatidadeNaoDesperdicada:
            type: number
          pesoLiquidoNaoDesperdicado:
            type: number
          mediaDesconto:
            type: number
        required:
          - produtoId
          - nome
          - valorPoupado
          - quantidadeNaoDesperdicada
          - pesoLiquidoNaoDesperdicado
          - mediaDesconto
      #xml lista Produtos nao desperdicados
      xml:
        name: ListaProdutosNaoDesperdicados
    #json utilizador criar conta
    Utilizador:
      type: object
      properties:
        nome:
          type: string
        apelido:
          type: string
        email:
          type: string
        password:
          type: string
        contacto:
          type: string
      required:
        - email
        - password  
      #xml utilizador criar conta
      xml:
        name: Utilizador
    #json utilizador iniciar sessão
    Login:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
      #xml utilizador iniciar sessao
      xml:
        name: Login
  requestBodies:
    Produto:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Produto'
        application/xml:
          schema:
            $ref: '#/components/schemas/Produto'
      description: Produto object que precisa de ser adicionado
      required: true
    UserArray:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Utilizador'
      description: Lista de utilizador object
      required: true
  securitySchemes:
    promovalidade_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
          scopes:
            'write:protudos': modificar os produtos na conta
            'read:produtos': ler os produtos
    api_key:
      type: apiKey
      name: api_key
      in: header